### ISSUE TITLE
Potential reentry vulnerability when withdrawing malicious erc20 tokens. 

### ISSUE THREAD

**Issue by yaronvel** [gnosis/dx-contracts#54]
```
    function withdraw(
        address tokenAddress,
        uint amount
    )
        public
        returns (uint)
    {
        uint usersBalance = balances[tokenAddress][msg.sender];
        amount = min(amount, usersBalance);

        // R1
        require(amount > 0);

        // R2
        require(Token(tokenAddress).transfer(msg.sender, amount));

        uint newBal = sub(usersBalance, amount);
        balances[tokenAddress][msg.sender] = newBal;

        NewWithdrawal(tokenAddress, amount);

        return newBal;
    }
```

It is better imo to have 
```
        uint newBal = sub(usersBalance, amount);
        balances[tokenAddress][msg.sender] = newBal;
```
before the `transfer` call.

This is very minor issue, as users have to trust erc20 tokens in any case. But since it is easy to avoid that need, you might as well do it.

**Comment by josojo** [comment]
Hi @yaronvel,

thank you for opening this issue. We completely share your thoughts.

This is something we will change with the next release, as your proposed version prevents reentrances completely and is a good practice. Though, the current code cannot be abused to steal any valuable tokens, as the re-entrance is only possible with scammy tokens.
