### ISSUE TITLE
Letting anyone call `claimSellerFunds` could confuse bot accounting

### ISSUE THREAD

**Issue by yaronvel** [gnosis/dx-contracts#56]
A bot that will try to estimate his total balance will read `balances` and `sellerBalances` and sum them.
However, this requires two web3 calls. and a malicious "attacker" might call `claimSellerFunds` between the two calls and mess up the bot accounting.

**Comment by josojo** [comment]
Yes, this might happen. 

But I think that an easier solution would be to change the bot logic to check the balances, then changing the smart contract.

A very simple fix would be to surround the calls for the `balances` and `sellerBalances` with calls for the `current block number` and then it could be checked whether block number calls return the same number.

Anyways the bots need to take care of more critical situations like reorgs etc.

**Comment by yaronvel** [comment]
Makes sense. Thanks.
